options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _REGION: "europe-central2"
  _AR_REPO: "apps"
  _IMAGE: "hello-build"

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build","-t",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE}:$SHORT_SHA",
        "."
      ]
    env:
      - "COMMIT_SHA=$SHORT_SHA"

  - name: gcr.io/cloud-builders/docker
    args:
      [
        "push",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE}:$SHORT_SHA"
      ]

  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -lc
      - |
        echo "Image pushed:"
        echo "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE}:$SHORT_SHA"

images:
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE}:$SHORT_SHA"
